import pandas as pd
import matplotlib.pyplot as plt

# ============================================================
# Load CSV generated by evaluate_aif_v3.py
# ============================================================
csv_path = "./aif_v3_eval_results_pure_efe.csv"
df = pd.read_csv(csv_path)

# ============================================================
# NeurIPS-style plot settings
# ============================================================
plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
    "font.size": 12,
    "axes.labelsize": 13,
    "axes.titlesize": 13,
    "legend.fontsize": 11,
    "xtick.labelsize": 11,
    "ytick.labelsize": 11,
    "axes.linewidth": 1.0,
    "lines.linewidth": 2.0,
    "lines.markersize": 5,
    "grid.alpha": 0.3,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
})

def beautify(ax):
    ax.grid(True, linestyle="--", alpha=0.3)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

def save_fig(name):
    plt.tight_layout()
    plt.savefig(f"{name}.pdf")
    plt.savefig(f"{name}.png")
    plt.show()

# ============================================================
# Summary statistics
# ============================================================
success_rate = df["success"].mean()
failure_rate = 1.0 - success_rate
avg_steps_success = df[df["success"] == 1]["steps"].mean()
avg_steps_all = df["steps"].mean()
avg_collisions = df["collisions"].mean()
avg_belief_err = df["belief_err"].mean()

print(f"Success rate: {success_rate:.3f}")
print(f"Failure rate: {failure_rate:.3f}")
print(f"Average steps successful only: {avg_steps_success:.2f}")
print(f"Average steps all trials: {avg_steps_all:.2f}")
print(f"Average collisions per trial: {avg_collisions:.3f}")
print(f"Mean belief error: {avg_belief_err:.4f}")

# ============================================================
# Figure 1: Success vs failure bar plot
# ============================================================
fig, ax = plt.subplots(figsize=(4.8, 4.0))

labels = ["Success", "Failure"]
values = [success_rate, failure_rate]

ax.bar(labels, values)
ax.set_ylabel("Rate")
ax.set_title("AIF V3 evaluation success rate")
ax.set_ylim(0, 1.05)

for i, v in enumerate(values):
    ax.text(i, v + 0.025, f"{v:.2f}", ha="center", va="bottom")

beautify(ax)
save_fig("aif_v3_success_failure_rate")

# ============================================================
# Figure 2: Steps per trial
# ============================================================
fig, ax = plt.subplots(figsize=(7.0, 4.0))

ax.plot(df["trial"], df["steps"], marker="o", label="Steps per trial")

failures = df[df["success"] == 0]
ax.scatter(
    failures["trial"],
    failures["steps"],
    marker="x",
    s=80,
    label="Failures / timeouts",
    zorder=5,
)

ax.axhline(avg_steps_all, linestyle="--", label=f"Mean steps = {avg_steps_all:.2f}")

ax.set_xlabel("Trial")
ax.set_ylabel("Steps")
ax.set_title("Steps required per evaluation trial")
beautify(ax)
ax.legend(frameon=False)

save_fig("aif_v3_steps_per_trial")

# ============================================================
# Figure 3: Step distribution for successful trials
# ============================================================
fig, ax = plt.subplots(figsize=(6.2, 4.0))

successful = df[df["success"] == 1]

ax.hist(successful["steps"], bins=15, edgecolor="black", alpha=0.8)
ax.axvline(avg_steps_success, linestyle="--", label=f"Mean = {avg_steps_success:.2f}")

ax.set_xlabel("Steps")
ax.set_ylabel("Number of successful trials")
ax.set_title("Distribution of steps for successful trials")
beautify(ax)
ax.legend(frameon=False)

save_fig("aif_v3_successful_steps_distribution")

# ============================================================
# Figure 4: Collisions per trial
# ============================================================
fig, ax = plt.subplots(figsize=(7.0, 4.0))

ax.bar(df["trial"], df["collisions"])
ax.axhline(avg_collisions, linestyle="--", label=f"Mean collisions = {avg_collisions:.2f}")

ax.set_xlabel("Trial")
ax.set_ylabel("Collisions")
ax.set_title("Collisions per evaluation trial")
beautify(ax)
ax.legend(frameon=False)

save_fig("aif_v3_collisions_per_trial")

# ============================================================
# Figure 5: Belief error per trial
# ============================================================
fig, ax = plt.subplots(figsize=(7.0, 4.0))

ax.plot(df["trial"], df["belief_err"], marker="o", label="Belief error rate")
ax.axhline(avg_belief_err, linestyle="--", label=f"Mean = {avg_belief_err:.4f}")

ax.set_xlabel("Trial")
ax.set_ylabel("Belief error rate")
ax.set_title("Belief error rate per trial")
beautify(ax)
ax.legend(frameon=False)

save_fig("aif_v3_belief_error_per_trial")

# ============================================================
# Figure 6: Compact summary bar plot
# ============================================================
fig, ax = plt.subplots(figsize=(6.4, 4.0))

summary_labels = [
    "Success\nrate",
    "Collision\nrate",
    "Belief\nerror",
    "Failure\nrate",
]

collision_rate = (df["collisions"] > 0).mean()

summary_values = [
    success_rate,
    collision_rate,
    avg_belief_err,
    failure_rate,
]

ax.bar(summary_labels, summary_values)
ax.set_ylabel("Rate")
ax.set_title("AIF V3 compact evaluation summary")
ax.set_ylim(0, 1.05)

for i, v in enumerate(summary_values):
    ax.text(i, v + 0.025, f"{v:.3f}", ha="center", va="bottom")

beautify(ax)

save_fig("aif_v3_compact_summary")